local box = require 'bump.box'

describe('bump.box', function()
  it('is a table', function()
    assert.equal(type(box), 'table')
  end)

  describe('.isIntersecting', function()
    it('returns true when two boxes geom', function()
      assert.truthy(box.isIntersecting(0,0,10,10, 5,5,10,10))
    end)
    it('returns false when two boxes do not geom', function()
      assert.falsy(box.isIntersecting(0,0,10,10, 20,20,10,10))
    end)
  end)

  describe('.getDisplacement', function()
    it('returns the minimum & total displacement vector needed to move box1 out of box2', function()
      assert.same({0,-6,-6,-6}, {box.getDisplacement(0,0,10,10, 4,4,10,10)})
      assert.same({0,-4,-4,-4}, {box.getDisplacement(0,0,10,10, 6,6,10,10)})
      assert.same({0,-5,-5,-5}, {box.getDisplacement(0,0,10,10, 5,5,10,10)})
    end)
  end)

  describe('.getSegmentIntersection', function()
    it('returns nothing if the segment and the box given are not intersecting', function()
      assert.Nil(box.getSegmentIntersection(0,0,20,20, 100,100, 200,200))
    end)
    it('returns the same point twice if the segment only touches the border of the box', function()
      assert.same({0,0,0,0}, {box.getSegmentIntersection(0,0,20,20, 0,0, 0,-10)})
    end)
    it('returns 2 points if the segment goes through the box', function()
      assert.same({0,10, 20,10}, {box.getSegmentIntersection(0,0,20,20, -10,10, 30,10)})
    end)
  end)
end)
